spring.application.name=testTask

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.liquibase=INFO
logging.level.org.testcontainers=INFO
logging.level.com.github.dockerjava=WARN

# ??????? API
external-api.url=https://catfact.ninja/fact
external-api.poll-rate-ms=60000

# Kafka producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

## ???????? ????? ? ???????????
spring.docker.compose.lifecycle-management=start-and-stop

spring.kafka.bootstrap-servers=localhost:9092

